In [1]:
%cd ..

/home/hien/Documents/models/reid/rep_reid


In [2]:
import torch

embeddings = torch.rand((5, 4))

embeddings_norm = torch.nn.functional.normalize(embeddings, p=2, dim=1)
embeddings, embeddings_norm


(tensor([[0.4158, 0.8490, 0.2749, 0.0218],
         [0.9741, 0.6428, 0.2425, 0.1630],
         [0.1165, 0.3331, 0.5887, 0.0424],
         [0.2851, 0.1925, 0.3518, 0.3293],
         [0.1848, 0.1419, 0.7527, 0.5218]]),
 tensor([[0.4222, 0.8621, 0.2792, 0.0222],
         [0.8097, 0.5343, 0.2015, 0.1355],
         [0.1694, 0.4844, 0.8561, 0.0616],
         [0.4815, 0.3252, 0.5942, 0.5562],
         [0.1955, 0.1502, 0.7964, 0.5522]]))

In [3]:
from src.metrics import self_cosine_dist, self_euclidean_dist

self_euclidean_dist(embeddings), self_euclidean_dist(embeddings_norm)
# Not-same

(tensor([[0.0000e+00, 3.7522e-01, 4.5452e-01, 5.4846e-01, 1.0315e+00],
         [3.7522e-01, 0.0000e+00, 9.6574e-01, 7.1710e-01, 1.2629e+00],
         [4.5452e-01, 9.6574e-01, 0.0000e+00, 1.8663e-01, 2.9798e-01],
         [5.4846e-01, 7.1710e-01, 1.8663e-01, 5.9605e-08, 2.1042e-01],
         [1.0315e+00, 1.2629e+00, 2.9798e-01, 2.1042e-01, 0.0000e+00]]),
 tensor([[ 0.0000e+00,  2.7647e-01,  5.4089e-01,  6.7626e-01,  1.1067e+00],
         [ 2.7647e-01,  0.0000e+00,  8.4621e-01,  4.8256e-01,  1.0522e+00],
         [ 5.4089e-01,  8.4621e-01,  1.1921e-07,  4.3593e-01,  3.5658e-01],
         [ 6.7626e-01,  4.8256e-01,  4.3593e-01,  0.0000e+00,  1.5334e-01],
         [ 1.1067e+00,  1.0522e+00,  3.5658e-01,  1.5334e-01, -1.1921e-07]]))

In [5]:
self_cosine_dist(embeddings), self_cosine_dist(embeddings_norm)
# Same

(tensor([[5.9605e-08, 1.3824e-01, 2.7045e-01, 3.3813e-01, 5.5337e-01],
         [1.3824e-01, 0.0000e+00, 4.2311e-01, 2.4128e-01, 5.2611e-01],
         [2.7045e-01, 4.2311e-01, 1.1921e-07, 2.1796e-01, 1.7829e-01],
         [3.3813e-01, 2.4128e-01, 2.1796e-01, 0.0000e+00, 7.6668e-02],
         [5.5337e-01, 5.2611e-01, 1.7829e-01, 7.6668e-02, 5.9605e-08]]),
 tensor([[ 0.0000e+00,  1.3824e-01,  2.7045e-01,  3.3813e-01,  5.5337e-01],
         [ 1.3824e-01,  0.0000e+00,  4.2311e-01,  2.4128e-01,  5.2611e-01],
         [ 2.7045e-01,  4.2311e-01,  0.0000e+00,  2.1796e-01,  1.7829e-01],
         [ 3.3813e-01,  2.4128e-01,  2.1796e-01,  0.0000e+00,  7.6668e-02],
         [ 5.5337e-01,  5.2611e-01,  1.7829e-01,  7.6668e-02, -1.1921e-07]]))

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
pdist = nn.PairwiseDistance(p=2)

input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
output = pdist(input1, input2)
output.shape

torch.Size([100])

In [3]:
input1 = torch.randn(100, 128)*100
input2 = torch.randn(100, 128)*100

In [29]:
input1 = torch.nn.functional.normalize(input1, dim=1)

In [30]:
import torch
import torch.nn as nn
output = torch.cdist(input1, input1)
output.mean()

tensor(1.3985)

In [31]:
dist_mat = torch.matmul(input1, input1.t())
dist_mat.mean()

tensor(0.0104)

In [32]:
def euclidean_dist(x, y):
    m, n = x.size(0), y.size(0)
    xx = torch.pow(x, 2).sum(1, keepdim=True).expand(m, n)
    yy = torch.pow(y, 2).sum(1, keepdim=True).expand(n, m).t()
    dist = xx + yy - 2 * torch.matmul(x, y.t())
    dist = dist.sqrt()  # for numerical stability
    return dist

In [33]:
import torch
import torch.nn as nn

input1 = torch.randn(100, 128)*100
input2 = torch.randn(100, 128)*100
output = euclidean_dist(input1, input2)
output.mean()

tensor(1600.3169)

In [34]:
import torch
import torch.nn as nn

input1 = torch.randn(100, 128)*100
input2 = torch.randn(100, 128)*100
output = F.cosine_similarity(input1, input2)
output.shape

torch.Size([100])

In [2]:
import torch
def euclidean_dist(x, y):
    m, n = x.size(0), y.size(0)
    xx = torch.pow(x, 2).sum(1, keepdim=True).expand(m, n)
    yy = torch.pow(y, 2).sum(1, keepdim=True).expand(n, m).t()
    dist = xx + yy - 2 * torch.matmul(x, y.t())
    dist = dist.clamp(min=1e-12).sqrt()  # for numerical stability
    return dist

In [4]:
input1 = torch.randn(100, 128)
euclidean_dist(input1, input1).mean()

tensor(15.8574)

In [13]:
torch.cdist(input1, input1).mean()

tensor(15.8574)

In [11]:
n = input1.shape[0]
# Compute pairwise distance, replace by the official when merged
# ||a-b||^2 = ||a||^2 -2<a,b> + ||b||^2
dist = torch.pow(input1, 2).sum(dim=1, keepdim=True).expand(n, n)
dist = dist + dist.t()
# dist.addmm_(1, -2, inputs, inputs.t())
dist = torch.addmm(input=dist, mat1=input1, mat2=input1.t(), alpha=-2, beta=1)
dist = dist.clamp(min=1e-12).sqrt()  # for numerical stability

dist.mean()

tensor(15.8574)