In [1]:
%cd ..

/home/hien/Documents/models/reid/person_reid


In [2]:
import torch

embeddings = torch.rand((5, 4))

embeddings_norm = torch.nn.functional.normalize(embeddings, p=2, dim=1)
embeddings, embeddings_norm


(tensor([[0.6412, 0.0702, 0.7688, 0.4587],
         [0.8049, 0.3255, 0.8375, 0.1489],
         [0.3559, 0.9747, 0.6264, 0.9222],
         [0.4555, 0.9372, 0.8192, 0.9561],
         [0.6587, 0.6458, 0.2381, 0.2820]]),
 tensor([[0.5811, 0.0636, 0.6968, 0.4157],
         [0.6622, 0.2678, 0.6890, 0.1225],
         [0.2337, 0.6400, 0.4113, 0.6055],
         [0.2787, 0.5734, 0.5013, 0.5850],
         [0.6630, 0.6500, 0.2396, 0.2838]]))

In [3]:
from src.metrics import self_cosine_dist, self_euclidean_dist

self_euclidean_dist(embeddings), self_euclidean_dist(embeddings_norm)
# Not-same


No module named 'metrics.rank_cylib.rank_cy'
No module named 'metrics.rank_cylib.rank_cy'


/home/hien/Documents/models/reid/person_reid/src/metrics/../metrics/mAP.py:17: UserWarning: Cython rank evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  "Cython rank evaluation (very fast so highly recommended) is "
/home/hien/Documents/models/reid/person_reid/src/metrics/mAP.py:17: UserWarning: Cython rank evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  "Cython rank evaluation (very fast so highly recommended) is "


(tensor([[0.0000, 0.1927, 1.1346, 1.0361, 0.6445],
         [0.1927, 0.0000, 1.2656, 1.1481, 0.5009],
         [1.1346, 1.2656, 0.0000, 0.0497, 0.7605],
         [1.0361, 1.1481, 0.0497, 0.0000, 0.9184],
         [0.6445, 0.5009, 0.7605, 0.9184, 0.0000]]),
 tensor([[0.0000e+00, 1.3431e-01, 5.7044e-01, 4.1824e-01, 5.7691e-01],
         [1.3431e-01, 0.0000e+00, 6.3259e-01, 4.8964e-01, 3.7399e-01],
         [5.7044e-01, 6.3259e-01, 2.3842e-07, 1.4974e-02, 3.1738e-01],
         [4.1824e-01, 4.8964e-01, 1.4974e-02, 0.0000e+00, 3.1271e-01],
         [5.7691e-01, 3.7399e-01, 3.1738e-01, 3.1271e-01, 0.0000e+00]]))

In [4]:
self_cosine_dist(embeddings), self_cosine_dist(embeddings_norm)
# Same


(tensor([[ 0.0000e+00,  6.7157e-02,  2.8522e-01,  2.0912e-01,  2.8845e-01],
         [ 6.7157e-02,  0.0000e+00,  3.1629e-01,  2.4482e-01,  1.8699e-01],
         [ 2.8522e-01,  3.1629e-01,  0.0000e+00,  7.4868e-03,  1.5869e-01],
         [ 2.0912e-01,  2.4482e-01,  7.4868e-03,  1.1921e-07,  1.5635e-01],
         [ 2.8845e-01,  1.8699e-01,  1.5869e-01,  1.5635e-01, -1.1921e-07]]),
 tensor([[ 0.0000e+00,  6.7157e-02,  2.8522e-01,  2.0912e-01,  2.8845e-01],
         [ 6.7157e-02,  0.0000e+00,  3.1629e-01,  2.4482e-01,  1.8699e-01],
         [ 2.8522e-01,  3.1629e-01,  0.0000e+00,  7.4868e-03,  1.5869e-01],
         [ 2.0912e-01,  2.4482e-01,  7.4868e-03, -1.1921e-07,  1.5635e-01],
         [ 2.8845e-01,  1.8699e-01,  1.5869e-01,  1.5635e-01, -1.1921e-07]]))

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

pdist = nn.PairwiseDistance(p=2)

input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
output = pdist(input1, input2)
output.shape


torch.Size([100])

In [6]:
input1 = torch.randn(100, 128) * 100
input2 = torch.randn(100, 128) * 100


In [7]:
input1 = torch.nn.functional.normalize(input1, dim=1)


In [8]:
import torch
import torch.nn as nn

output = torch.cdist(input1, input1)
output.mean()


tensor(1.3984)

In [9]:
dist_mat = torch.matmul(input1, input1.t())
dist_mat.mean()


tensor(0.0104)

In [10]:
def euclidean_dist(x, y):
    m, n = x.size(0), y.size(0)
    xx = torch.pow(x, 2).sum(1, keepdim=True).expand(m, n)
    yy = torch.pow(y, 2).sum(1, keepdim=True).expand(n, m).t()
    dist = xx + yy - 2 * torch.matmul(x, y.t())
    dist = dist.sqrt()  # for numerical stability
    return dist


In [11]:
import torch
import torch.nn as nn

input1 = torch.randn(100, 128) * 100
input2 = torch.randn(100, 128) * 100
output = euclidean_dist(input1, input2)
output.mean()


tensor(1594.9022)

In [12]:
import torch
import torch.nn as nn

input1 = torch.randn(100, 128) * 100
input2 = torch.randn(100, 128) * 100
output = F.cosine_similarity(input1, input2)
output.shape


torch.Size([100])

In [13]:
import torch


def euclidean_dist(x, y):
    m, n = x.size(0), y.size(0)
    xx = torch.pow(x, 2).sum(1, keepdim=True).expand(m, n)
    yy = torch.pow(y, 2).sum(1, keepdim=True).expand(n, m).t()
    dist = xx + yy - 2 * torch.matmul(x, y.t())
    dist = dist.clamp(min=1e-12).sqrt()  # for numerical stability
    return dist


In [14]:
input1 = torch.randn(100, 128)
euclidean_dist(input1, input1).mean()


tensor(15.8767)

In [15]:
torch.cdist(input1, input1).mean()


tensor(15.8767)

In [16]:
n = input1.shape[0]
# Compute pairwise distance, replace by the official when merged
# ||a-b||^2 = ||a||^2 -2<a,b> + ||b||^2
dist = torch.pow(input1, 2).sum(dim=1, keepdim=True).expand(n, n)
dist = dist + dist.t()
# dist.addmm_(1, -2, inputs, inputs.t())
dist = torch.addmm(input=dist, mat1=input1, mat2=input1.t(), alpha=-2, beta=1)
dist = dist.clamp(min=1e-12).sqrt()  # for numerical stability

dist.mean()


tensor(15.8767)

# Hamming distance

In [46]:
target = torch.tensor([[0, 1, 0, 1, 1]])
preds = torch.tensor([[1, 0, 0, 1, 0]])

In [47]:
dim = preds.shape[1]

x = (preds - 0.5) * 2
x


tensor([[ 1., -1., -1.,  1., -1.]])

In [48]:
y = (target - 0.5) * 2
y


tensor([[-1.,  1., -1.,  1.,  1.]])

- gn: Số lượng điểm giống nhau giữa hai vector
- kn: Số lượng điểm khác nhau giữa hai vector

In [50]:
torch.mm(x, y.t())
# = gn - kn


tensor([[-1.]])

In [51]:
torch.mm(x, y.t()) + dim
# (gn - kn) + (gn + kn) = 2gn


tensor([[4.]])

In [52]:
(torch.mm(x, y.t()) + dim) / 2
# (gn - kn + gn + kn) = (2gn) / 2


tensor([[2.]])

In [54]:
dim - (torch.mm(x, y.t()) + dim) / 2
# (gn + kn) - (gn) = kn


tensor([[3.]])